# Use the Node.js base image
FROM node:18.17.1

# Set the working directory
WORKDIR /app

# Set environment variables
ENV PORT=3000
ENV MODEL_URL='https://storage.googleapis.com/project-dicoding-cancer-dectection-model/model.json'

# Copy package.json and package-lock.json (if available) first for better build caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "start" ]
